import Head from "next/head";
import Image from "next/image";
import {
  Box,
  Code,
  Flex,
  GridItem,
  Heading,
  Link,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";

interface CardProps {
  href: string;
  title: string;
  description: string;
}

const Card = ({ href, title, description }: CardProps) => (
  <GridItem
    as="a"
    href={href}
    m={4}
    p={6}
    textDecor="none"
    borderWidth={1}
    rounded="lg"
    transitionDuration="normal"
    _hover={{
      color: "blue.600",
      borderColor: "blue.600",
    }}
  >
    <Heading m={0} mb={6} fontSize="2xl">
      {title} &rarr;
    </Heading>
    <Text m={0} fontSize="lg" lineHeight={1.5}>
      {description}
    </Text>
  </GridItem>
);

const Home: NextPage = () => (
  <Flex
    direction="column"
    justify={["flex-start", "center"]}
    align="center"
    h="100%"
  >
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Flex
      as="main"
      direction="column"
      align="center"
      justify="center"
      flex={1}
      px={6}
    >
      <Heading as="h1" m={0} lineHeight={1.15} fontSize="4rem">
        Welcome to{" "}
        <Link
          href="https://nextjs.org"
          color="blue.600"
          textDecor="none"
          _hover={{ textDecor: "underline" }}
        >
          Next.js!
        </Link>
      </Heading>

      <Text lineHeight={1.5} fontSize="2xl" my={8}>
        Get started by editing <Code fontSize="inherit">pages/index.js</Code>
      </Text>

      <SimpleGrid columns={[1, 2]} mt={12} maxW="800px">
        <Card
          href="https://nextjs.org/docs"
          title="Documentation"
          description="Find in-depth information about Next.js features and API."
        />

        <Card
          href="https://nextjs.org/learn"
          title="Learn"
          description="Learn about Next.js in an interactive course with quizzes!"
        />

        <Card
          href="https://github.com/vercel/next.js/tree/master/examples"
          title="Examples"
          description="Discover and deploy boilerplate example Next.js projects."
        />

        <Card
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          title="Deploy"
          description="Instantly deploy your Next.js site to a public URL with Vercel."
        />
      </SimpleGrid>
    </Flex>

    <Flex
      as="footer"
      w="100%"
      h="100px"
      borderTopWidth={1}
      align="center"
      justify="center"
      flexShrink={0}
    >
      <Link
        as={Flex}
        justify="center"
        align="center"
        isExternal
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      >
        Powered by{" "}
        <Box h="1em" ml={2}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </Box>
      </Link>
    </Flex>
  </Flex>
);

export default Home;
